import { defineConfig } from 'vite';
import { readFileSync, copyFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';

const legacyScripts = ['app.js', 'sync.js', 'event-log.js', 'fractional-index.js', 'styles.css'];

function syncConfigPlugin() {
  const generateSyncConfig = () => {
    const url = process.env.SUPABASE_URL || '';
    const anonKey = process.env.SUPABASE_ANON_KEY || '';
    const bearerToken = process.env.SYNC_BEARER_TOKEN || '';
    const schema = process.env.SUPABASE_SCHEMA || 'public';

    return `// Generated by Vite syncConfigPlugin — do not edit
(function() {
  // Skip in test mode
  var isTestMode = new URLSearchParams(window.location.search).get('test-mode') === '1';
  if (isTestMode) {
    console.log('[Sync Config] Test mode - skipping config');
    return;
  }

  window.SYNC_SUPABASE_URL = ${JSON.stringify(url)};
  window.SYNC_SUPABASE_ANON_KEY = ${JSON.stringify(anonKey)};
  window.SYNC_BEARER_TOKEN = ${JSON.stringify(bearerToken)};
  window.SYNC_SUPABASE_SCHEMA = ${JSON.stringify(schema)};
  window.SYNC_API_URL = window.location.origin;

  console.log('[Sync Config] Credentials loaded for', window.SYNC_SUPABASE_URL);
})();
`;
  };

  return {
    name: 'sync-config',
    configureServer(server) {
      server.middlewares.use('/sync-config.js', (_req, res) => {
        res.setHeader('Content-Type', 'application/javascript');
        res.end(generateSyncConfig());
      });
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'sync-config.js',
        source: generateSyncConfig(),
      });
    },
  };
}

function copyLegacyScripts() {
  return {
    name: 'copy-legacy-scripts',
    writeBundle(options) {
      const outDir = options.dir || 'dist';
      for (const file of legacyScripts) {
        const src = resolve(__dirname, file);
        const dest = resolve(outDir, file);
        try {
          copyFileSync(src, dest);
        } catch (e) {
          console.warn(`Warning: could not copy ${file}: ${e.message}`);
        }
      }
    },
  };
}

export default defineConfig({
  plugins: [syncConfigPlugin(), copyLegacyScripts()],
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
    },
  },
  build: {
    rollupOptions: {
      input: resolve(__dirname, 'index.html'),
    },
  },
});
