ALTER TABLE items ADD COLUMN IF NOT EXISTS type_updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE items ADD COLUMN IF NOT EXISTS level_updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE items ADD COLUMN IF NOT EXISTS indented_updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
